# Spring Boot configuration
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL} #jdbc:postgresql://localhost:5432/isadb
    username: ${JDBC_DATABASE_USERNAME} #isa 
    password: ${JDBC_DATABASE_PASSWORD} #isa 
    initialization-mode: always
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop #create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  # RabbitMQ ONLY WHEN USING ON LOCAL MACHINE
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: vmaqngrm
#    password: BHAFy2pYqDLrQxDduUD-03HH-N0ACEVW
  mail:
    host: smtp.gmail.com
    port: 587
    username: schnabelpharmacy@gmail.com
    password: 24WiSKVFDnAQDRC
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

mail:
  smtp:
    debug: true
custom:
  addr: ${SCHNABEL_FRONTEND_ADDR}
  fport: ${SCHNABEL_FRONTEND_PORT}
  port: ${SCHNABEL_BACKEND_PORT}
  jwtSecret: ${SCHNABEL_JWT_SECRET}
  jwtExpMin: 1
  refSecret: ${SCHNABEL_REF_SECRET}
  refExpMonth: 6
  max_penalties: 3
file:
  upload-dir: /schnabel/images
